### ISSUE TITLE
wav files error

### ISSUE THREAD

**Issue by netsafe** [MainRo/deepspeech-server#17]
Compiled it all but WAV files are "not understood"

    STT error: File format b''... not understood.

**Comment by MainRo** [comment]
This error comes from the wav reader of scipy (scipy.io.wavfile.read). So the provided wav file contains a header not supported by scipy. I think that I saw similar issues with the timit dataset and I re-encoded them with sox.
Do you have information on the wav file you use ? or maybe a link to it if it is freely available ?

**Comment by netsafe** [comment]
This one - it's totally OK to use it :) Just a test of my own - recorded with latest Audacity on Windows 10 64 bit, any program plays it OK - on windows and android I've tested a lot of software - not a single failure playing it

[dstest1.zip](https://github.com/MainRo/deepspeech-server/files/2431498/dstest1.zip)

**Comment by netsafe** [comment]
Update: recompiling deepspeech and tensorflow from the source fixes the "warning problem" - but the recognition is totally inaccurate. Try the file I've attached and see for yourself

**Comment by MainRo** [comment]
The model provided by mozilla is trained with the Fisher, LibriSpeech, and Switchboard datasets, which probably do not contain enough samples for a fully functional STT system. This is only the 0.2 release :)

See here for information on the training:
https://github.com/mozilla/DeepSpeech/releases

You can train your own model with other datasets if you have more complete ones (eventually with the common voice one currently being built by mozilla: https://voice.mozilla.org/en/data).

I Close this issue because it is not related to the server.

**Comment by netsafe** [comment]
Well, I've found the problem :) The thing is that you **have to** build tensorflow+deepspeech all the way from a sources. After doing this with the latest mozilla tensorflow fork and deepspeech 0.2.1a - the error message is gone completely

**Comment by yinshengabc** [comment]
> Update: recompiling deepspeech and tensorflow from the source fixes the "warning problem" - but the recognition is totally inaccurate. Try the file I've attached and see for yourself

Hi, is this problem occurs when you POST the request from client web? I have no problem when run  'curl -X POST --data-binary @testfile.wav http://localhost:8080/stt' in the terminal but meet the same error when using the web to POST request. Also, do you mean that rebuild the source of tensorflow and deepspeech on windows can solve this problem?
