### ISSUE TITLE
add support of other audio formats

### ISSUE THREAD

**Issue by MainRo** [MainRo/deepspeech-server#18]
Using the pyav package would allow to support more audio formats that just wav single channel at 16khz.

**Comment by alexcannan** [comment]
[DeepSpeech's Python client has a sample-rate converter](https://github.com/mozilla/DeepSpeech/blob/5740d64e6ea10c961fa6dca924d7c8fe0baff659/native_client/python/client.py#L22) that could be implemented in the deepspeech.py file fairly easily. Happy to put together a PR if wanted

edit: just realizing this is a bit different since it's working on binary data and can't reference a local filepath, but the sox solution should work.

**Comment by MainRo** [comment]
yes, sox could work but requires to go through files. This is why I considered pyav, so that we can work directly on buffers.
