### ISSUE TITLE
Running Deepspeech on the Raspberry Pi 4

### ISSUE THREAD

**Issue by flatsiedatsie** [MainRo/deepspeech-server#22]
A few questions:
- Would the Raspberry Pi 4 have enough power/ram to run this well?
- Would the CPU or GPU option be best/available?

**Comment by MainRo** [comment]
It should be possible to run it on a rpi, but probably with significant latency on the answers. If you use pre-trained models from mozilla, you can try to use the pbmm one, which should use less memory. Mozilla also generates tflite models but these will not work with deepspeech-server because it does not support tflite runtime.

You can only use the CPU because the GPU of the rpi is not supported by tensorflow (AFAIK).
