### ISSUE TITLE
Connect this deepspeech-server by Android

### ISSUE THREAD

**Issue by tachen-cs** [MainRo/deepspeech-server#29]
HI, I am wondering can we connect this http server and use the deepspeech-server remotely by an Android device?
Like using the phone to join the local area network with the deespeech-server, and send the HTTP request by the phone?

So that, we might be able to record some audio directly by phones and send the audio files directly to deepspeech-server remotely.

May you give me some hints or simple codes so that I can have a try?

Thank you very much!

**Comment by MainRo** [comment]
Yes this is something possible. If you use a native app, then this should work directly. If you use a web browser, then CORS may be needed if your web application is served from another domain than deepspeech server. In any case you should use an https proxy in front of deepspeech-server to crypt data on the network.
There are many http(s) clients available on android. It will depend if you use java or kotlin. Not sure I can help more, it's been a while since I developed on Android.
