### ISSUE TITLE
[Feature Request] Add support for S3 paths

### ISSUE THREAD

**Issue by mlaradji** [MainRo/deepspeech-server#38]
I'm posting this as an issue to get some feedback. I'm happy to work on this myself.

In my pipeline, many of the audio files I want to transcribe are stored in S3. Currently, I have a service sitting in front of `deepspeech-server` that downloads the entire audio file from S3 and forwards it to `deepspeech-server`. The services live in the same server so there's no issue with bandwidth, but it does seem to be a waste of time and RAM.

A solution would be to allow `deepspeech-server` to directly access S3 files. It is easy to do using the `smart_open` package, which allows you to `open` an S3 path (also Hadoop, etc.) as a file-like object that we can directly use for inference. This would save even more time if we were to use the streaming inference API as well (#16).

**Comment by MainRo** [comment]
Concerning the access of audio data from s3 instead of http content: 
Do you sill need an http API for each request or instead do you need batch inference ? In the first case, then I think this may be a nice addition. In the latter case, then probably another dedicated tool is needed (we may add it to this package though, maybe it could also just be a dedicated http endpoint to the existing service).

Then concerning the technical side, unfortunately smart-open is not a viable choice for ds-server because it is a blocking API, while all IOs are synchronous (via asyncio) in ds-server. You may still try it on your side, I already have an rxpy operator available for it here: https://rxsci.readthedocs.io/en/latest/operators_io.html#rxsci.io.read. The file argument is anything supported by smart-open and you can set the config/credentials in transport_params (I still need to update the doc). But be aware that any network delay will block the whole service.
To integrate s3 in ds-server, we need an asynchronous s3 cyclotron driver (cyclotron is the reactive app framework used by ds-server). This is on my todo list for some time, based on https://github.com/aio-libs/aiobotocore, and eventually wrapping it on a smart-open like API (but fully asynchronous).
